import type { Role } from "@/lib/roles/types";

/**
 * Product, design, business and everything else.
 *
 * These four categories share a file because they share a maintenance rhythm:
 * their titles are stable, they change far more slowly than the engineering
 * ones, and nobody needs to edit them when a new AI job title appears.
 *
 * Aliases matter less here than in the technical catalogues -- people search for
 * "Product Manager" by typing "Product Manager" -- but the abbreviations that do
 * exist are heavily used ("PM", "BA", "UX", "HR", "TPM"), and a search for one
 * of those returning nothing looks like a missing catalogue rather than a
 * missing alias.
 */

export const PRODUCT_ROLES: Role[] = [
  {
    id: "product-manager",
    name: "Product Manager",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["PM", "Product", "Product Owner"],
    description: "Decides what gets built and why, and owns the outcome.",
    suggested: true,
    popular: true,
  },
  {
    id: "technical-product-manager",
    name: "Technical Product Manager",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["TPM", "Technical PM", "PM"],
    description: "Product management for developer-facing or infrastructure products.",
    popular: true,
  },
  {
    id: "data-product-manager",
    name: "Data Product Manager",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["Data PM", "PM", "Data"],
    description: "Owns data platforms and the products built on top of them.",
  },
  {
    id: "product-owner",
    name: "Product Owner",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["PO", "Scrum Product Owner"],
    description: "Owns and orders the backlog for a delivery team.",
    popular: true,
  },
  {
    id: "product-analyst",
    name: "Product Analyst",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["Product Analytics"],
    description: "Measures how a product is actually used and what to change.",
  },
  {
    id: "product-operations-manager",
    name: "Product Operations Manager",
    categoryId: "product-management",
    subcategory: "Product",
    aliases: ["Product Ops"],
    description: "Keeps product processes, tooling and reporting running.",
  },
  {
    id: "program-manager",
    name: "Program Manager",
    categoryId: "product-management",
    subcategory: "Delivery",
    aliases: ["PgM", "Programme Manager"],
    description: "Runs a set of related projects towards one outcome.",
  },
  {
    id: "technical-program-manager",
    name: "Technical Program Manager",
    categoryId: "product-management",
    subcategory: "Delivery",
    aliases: ["TPM", "Technical Programme Manager"],
    description: "Coordinates complex cross-team engineering delivery.",
    popular: true,
  },
  {
    id: "project-manager",
    name: "Project Manager",
    categoryId: "product-management",
    subcategory: "Delivery",
    aliases: ["PM", "Project Management"],
    description: "Plans, tracks and lands a defined piece of work.",
    popular: true,
  },
  {
    id: "delivery-manager",
    name: "Delivery Manager",
    categoryId: "product-management",
    subcategory: "Delivery",
    aliases: ["Delivery Lead"],
    description: "Owns the flow of work from commitment to release.",
  },
  {
    id: "engineering-manager",
    name: "Engineering Manager",
    categoryId: "product-management",
    subcategory: "Engineering Leadership",
    aliases: ["EM", "Software Engineering Manager", "Dev Manager"],
    description: "Leads an engineering team: people, delivery and technical direction.",
    popular: true,
  },
  {
    id: "engineering-project-manager",
    name: "Engineering Project Manager",
    categoryId: "product-management",
    subcategory: "Engineering Leadership",
    aliases: ["Engineering PM"],
    description: "Runs engineering projects end to end alongside the technical lead.",
  },
  {
    id: "scrum-master",
    name: "Scrum Master",
    categoryId: "product-management",
    subcategory: "Agile",
    aliases: ["Scrum", "Agile"],
    description: "Facilitates a scrum team and removes what blocks it.",
    popular: true,
  },
  {
    id: "agile-coach",
    name: "Agile Coach",
    categoryId: "product-management",
    subcategory: "Agile",
    aliases: ["Agile", "Scrum"],
    description: "Improves how multiple teams plan and deliver.",
  },
];

export const DESIGN_ROLES: Role[] = [
  {
    id: "ui-ux-designer",
    name: "UI/UX Designer",
    categoryId: "design",
    subcategory: "Product Design",
    aliases: ["UI", "UX", "UI UX", "UX/UI", "Designer"],
    description: "Designs both the interface and the flow a person moves through.",
    suggested: true,
    popular: true,
  },
  {
    id: "ux-designer",
    name: "UX Designer",
    categoryId: "design",
    subcategory: "Product Design",
    aliases: ["UX", "User Experience", "Designer"],
    description: "Designs how a product works before deciding how it looks.",
    popular: true,
  },
  {
    id: "ui-designer",
    name: "UI Designer",
    categoryId: "design",
    subcategory: "Product Design",
    aliases: ["UI", "User Interface", "Designer"],
    description: "Designs the visual surface: layout, type, colour and components.",
    popular: true,
  },
  {
    id: "product-designer",
    name: "Product Designer",
    categoryId: "design",
    subcategory: "Product Design",
    aliases: ["Designer", "UX", "UI"],
    description: "Owns a product area end to end, from problem to shipped interface.",
    popular: true,
  },
  {
    id: "interaction-designer",
    name: "Interaction Designer",
    categoryId: "design",
    subcategory: "Product Design",
    aliases: ["IxD", "UX"],
    description: "Designs the behaviour of an interface: states, motion and response.",
  },
  {
    id: "ux-researcher",
    name: "UX Researcher",
    categoryId: "design",
    subcategory: "Research",
    aliases: ["User Researcher", "UXR", "UX", "Research"],
    description: "Finds out what users actually need and whether a design works.",
    popular: true,
  },
  {
    id: "design-systems-designer",
    name: "Design Systems Designer",
    categoryId: "design",
    subcategory: "Design Systems",
    aliases: ["Design System", "UI"],
    description: "Builds and maintains the shared component and token library.",
  },
  {
    id: "design-systems-engineer",
    name: "Design Systems Engineer",
    categoryId: "design",
    subcategory: "Design Systems",
    aliases: ["Design System", "UI Engineer", "Frontend"],
    description: "Implements the design system as production front-end code.",
  },
  {
    id: "ux-engineer",
    name: "UX Engineer",
    categoryId: "design",
    subcategory: "Design Systems",
    aliases: ["UXE", "UI Engineer", "Frontend", "UX"],
    description: "Sits between design and engineering, prototyping in real code.",
  },
  {
    id: "visual-designer",
    name: "Visual Designer",
    categoryId: "design",
    subcategory: "Visual",
    aliases: ["Designer", "Graphic"],
    description: "Owns the visual language across a product or brand.",
  },
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    categoryId: "design",
    subcategory: "Visual",
    aliases: ["Designer", "Graphics"],
    description: "Designs brand, marketing and print material.",
    popular: true,
  },
  {
    id: "motion-designer",
    name: "Motion Designer",
    categoryId: "design",
    subcategory: "Visual",
    aliases: ["Motion Graphics", "Animation", "Designer"],
    description: "Designs animation and motion for product and marketing.",
  },
  {
    id: "creative-designer",
    name: "Creative Designer",
    categoryId: "design",
    subcategory: "Visual",
    aliases: ["Creative", "Designer"],
    description: "Works across campaigns, brand and concept work.",
  },
  {
    id: "design-lead",
    name: "Design Lead",
    categoryId: "design",
    subcategory: "Leadership",
    aliases: ["Lead Designer", "Head of Design", "Designer"],
    description: "Leads a design team and owns the quality bar.",
  },
];

export const BUSINESS_ROLES: Role[] = [
  // -- Analysis and consulting ---------------------------------------------
  {
    id: "business-analyst",
    name: "Business Analyst",
    categoryId: "business",
    subcategory: "Analysis",
    aliases: ["BA", "Business Analysis"],
    description: "Turns business problems into requirements a team can build.",
    suggested: true,
    popular: true,
  },
  {
    id: "technical-business-analyst",
    name: "Technical Business Analyst",
    categoryId: "business",
    subcategory: "Analysis",
    aliases: ["Technical BA", "BA"],
    description: "A business analyst working close to the system design itself.",
  },
  {
    id: "strategy-analyst",
    name: "Strategy Analyst",
    categoryId: "business",
    subcategory: "Analysis",
    aliases: ["Strategy", "Corporate Strategy"],
    description: "Analyses markets and options to inform where the business goes.",
  },
  {
    id: "operations-analyst",
    name: "Operations Analyst",
    categoryId: "business",
    subcategory: "Analysis",
    aliases: ["Ops Analyst", "Operations"],
    description: "Measures and improves how the business actually runs day to day.",
  },
  {
    id: "process-analyst",
    name: "Process Analyst",
    categoryId: "business",
    subcategory: "Analysis",
    aliases: ["Business Process", "Process Improvement"],
    description: "Maps and redesigns business processes.",
  },
  {
    id: "operations-manager",
    name: "Operations Manager",
    categoryId: "business",
    subcategory: "Operations",
    aliases: ["Ops Manager", "Operations"],
    description: "Runs the operational function and the people in it.",
    popular: true,
  },
  {
    id: "management-consultant",
    name: "Management Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Consultant", "Strategy Consultant"],
    description: "Advises organisations on strategy, structure and change.",
    popular: true,
  },
  {
    id: "technology-consultant",
    name: "Technology Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Tech Consultant", "Consultant", "IT Consultant"],
    description: "Advises clients on technology choices and delivery.",
  },
  {
    id: "it-consultant",
    name: "IT Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Consultant", "Technology Consultant"],
    description: "Advises on IT systems, migration and operations.",
  },
  {
    id: "technical-consultant",
    name: "Technical Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Consultant"],
    description: "Hands-on consulting: implements as well as advises.",
  },
  {
    id: "solutions-consultant",
    name: "Solutions Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Presales", "Solution Consultant", "Consultant"],
    description: "Shapes how a product solves a specific customer's problem.",
  },
  {
    id: "business-consultant",
    name: "Business Consultant",
    categoryId: "business",
    subcategory: "Consulting",
    aliases: ["Consultant"],
    description: "Advises on commercial and operational improvement.",
  },

  // -- Sales, marketing and customer ----------------------------------------
  {
    id: "sales-engineer",
    name: "Sales Engineer",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["Presales", "SE", "Solutions Engineer"],
    description: "The technical half of a sales conversation: demos and proofs.",
    popular: true,
  },
  {
    id: "technical-sales-engineer",
    name: "Technical Sales Engineer",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["Presales", "Sales Engineer"],
    description: "Sells technical products by proving they fit.",
  },
  {
    id: "account-executive",
    name: "Account Executive",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["AE", "Sales"],
    description: "Owns the sales cycle from qualified lead to closed deal.",
    popular: true,
  },
  {
    id: "sales-development-representative",
    name: "Sales Development Representative",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["SDR", "BDR", "Sales"],
    description: "Opens conversations and qualifies pipeline.",
  },
  {
    id: "business-development-executive",
    name: "Business Development Executive",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["BDE", "BD", "Business Development"],
    description: "Finds and opens new commercial opportunities.",
  },
  {
    id: "business-development-manager",
    name: "Business Development Manager",
    categoryId: "business",
    subcategory: "Sales",
    aliases: ["BDM", "BD", "Business Development"],
    description: "Owns partnerships and new market growth.",
    popular: true,
  },
  {
    id: "technical-account-manager",
    name: "Technical Account Manager",
    categoryId: "business",
    subcategory: "Customer",
    aliases: ["TAM", "Account Manager"],
    description: "The technical owner of an existing customer relationship.",
  },
  {
    id: "customer-success-manager",
    name: "Customer Success Manager",
    categoryId: "business",
    subcategory: "Customer",
    aliases: ["CSM", "Customer Success"],
    description: "Keeps customers getting value, and keeps them renewing.",
    popular: true,
  },
  {
    id: "customer-support-specialist",
    name: "Customer Support Specialist",
    categoryId: "business",
    subcategory: "Customer",
    aliases: ["Support", "Customer Service"],
    description: "Resolves customer problems directly.",
  },
  {
    id: "technical-support-engineer",
    name: "Technical Support Engineer",
    categoryId: "business",
    subcategory: "Customer",
    aliases: ["Support Engineer", "Technical Support", "Support"],
    description: "Diagnoses and resolves technical issues for customers.",
    popular: true,
  },
  {
    id: "digital-marketing-specialist",
    name: "Digital Marketing Specialist",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Digital Marketing", "Marketing"],
    description: "Runs paid, organic and lifecycle marketing channels.",
    popular: true,
  },
  {
    id: "digital-marketing-manager",
    name: "Digital Marketing Manager",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Marketing Manager", "Digital Marketing", "Marketing"],
    description: "Owns digital channels and the team running them.",
  },
  {
    id: "seo-specialist",
    name: "SEO Specialist",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["SEO", "Search Engine Optimisation", "Marketing"],
    description: "Grows organic search traffic and the content behind it.",
  },
  {
    id: "content-strategist",
    name: "Content Strategist",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Content", "Content Marketing", "Marketing"],
    description: "Decides what content gets made and why.",
  },
  {
    id: "product-marketing-manager",
    name: "Product Marketing Manager",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["PMM", "Product Marketing", "Marketing"],
    description: "Positions the product and arms the go-to-market teams.",
    popular: true,
  },
  {
    id: "growth-marketing-manager",
    name: "Growth Marketing Manager",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Growth", "Growth Marketer", "Marketing"],
    description: "Runs experiments against acquisition and retention metrics.",
  },
  {
    id: "brand-manager",
    name: "Brand Manager",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Brand", "Marketing"],
    description: "Owns how the brand is expressed and perceived.",
  },
  {
    id: "market-research-analyst",
    name: "Market Research Analyst",
    categoryId: "business",
    subcategory: "Marketing",
    aliases: ["Market Research", "Research", "Marketing"],
    description: "Studies markets, competitors and customer segments.",
  },

  // -- People ---------------------------------------------------------------
  {
    id: "hr-specialist",
    name: "HR Specialist",
    categoryId: "business",
    subcategory: "People",
    aliases: ["HR", "Human Resources"],
    description: "Handles the operational side of the employee lifecycle.",
    popular: true,
  },
  {
    id: "hr-manager",
    name: "HR Manager",
    categoryId: "business",
    subcategory: "People",
    aliases: ["HR", "Human Resources"],
    description: "Leads the HR function for a business or region.",
  },
  {
    id: "hr-business-partner",
    name: "HR Business Partner",
    categoryId: "business",
    subcategory: "People",
    aliases: ["HRBP", "HR", "Human Resources"],
    description: "Partners with a business unit on people strategy.",
  },
  {
    id: "technical-recruiter",
    name: "Technical Recruiter",
    categoryId: "business",
    subcategory: "People",
    aliases: ["Tech Recruiter", "Recruiter", "Recruitment", "Talent"],
    description: "Hires engineers, and can hold a technical conversation while doing it.",
    popular: true,
  },
  {
    id: "it-recruiter",
    name: "IT Recruiter",
    categoryId: "business",
    subcategory: "People",
    aliases: ["Recruiter", "Recruitment", "Talent"],
    description: "Recruits across IT and technology functions.",
  },
  {
    id: "talent-acquisition-specialist",
    name: "Talent Acquisition Specialist",
    categoryId: "business",
    subcategory: "People",
    aliases: ["TA", "Talent Acquisition", "Recruiter", "Recruitment"],
    description: "Owns sourcing and the candidate experience end to end.",
  },
  {
    id: "talent-acquisition-manager",
    name: "Talent Acquisition Manager",
    categoryId: "business",
    subcategory: "People",
    aliases: ["TA Manager", "Talent Acquisition", "Recruitment"],
    description: "Leads the recruiting function and its hiring plan.",
  },
  {
    id: "recruitment-coordinator",
    name: "Recruitment Coordinator",
    categoryId: "business",
    subcategory: "People",
    aliases: ["Recruiting Coordinator", "Recruitment", "Talent"],
    description: "Keeps interview scheduling and candidate logistics running.",
  },
  {
    id: "people-operations-specialist",
    name: "People Operations Specialist",
    categoryId: "business",
    subcategory: "People",
    aliases: ["People Ops", "HR"],
    description: "Builds the systems and processes people teams run on.",
  },
  {
    id: "learning-and-development-specialist",
    name: "Learning and Development Specialist",
    categoryId: "business",
    subcategory: "People",
    aliases: ["L&D", "Learning and Development", "Training", "HR"],
    description: "Designs and runs training and capability programmes.",
  },

  // -- Finance --------------------------------------------------------------
  {
    id: "financial-analyst",
    name: "Financial Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Finance Analyst", "Finance", "FP&A"],
    description: "Models performance and supports financial decisions.",
    popular: true,
  },
  {
    id: "investment-analyst",
    name: "Investment Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Investment", "Finance", "Equity Research"],
    description: "Researches and evaluates investment opportunities.",
  },
  {
    id: "risk-analyst",
    name: "Risk Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Risk", "Finance"],
    description: "Identifies and quantifies financial and operational risk.",
  },
  {
    id: "credit-analyst",
    name: "Credit Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Credit", "Finance"],
    description: "Assesses creditworthiness and lending exposure.",
  },
  {
    id: "accountant",
    name: "Accountant",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Accounting", "Finance"],
    description: "Maintains the books and produces financial statements.",
    popular: true,
  },
  {
    id: "financial-controller",
    name: "Financial Controller",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Controller", "Finance", "Accounting"],
    description: "Owns reporting, controls and the close process.",
  },
  {
    id: "auditor",
    name: "Auditor",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Audit", "Internal Audit", "Finance"],
    description: "Tests whether controls and records hold up.",
  },
  {
    id: "tax-analyst",
    name: "Tax Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Tax", "Finance"],
    description: "Handles tax compliance, filings and planning.",
  },
  {
    id: "fintech-developer",
    name: "FinTech Developer",
    categoryId: "business",
    subcategory: "FinTech",
    aliases: ["FinTech", "Financial Technology", "Payments"],
    description: "Builds financial products: payments, ledgers and compliance.",
    popular: true,
  },
  {
    id: "fintech-engineer",
    name: "FinTech Engineer",
    categoryId: "business",
    subcategory: "FinTech",
    aliases: ["FinTech", "Financial Technology", "Payments"],
    description: "Engineers financial systems where correctness is non-negotiable.",
  },
  {
    id: "quantitative-developer",
    name: "Quantitative Developer",
    categoryId: "business",
    subcategory: "FinTech",
    aliases: ["Quant Developer", "Quant", "Quantitative"],
    description: "Implements trading and pricing models in production code.",
  },
  {
    id: "banking-analyst",
    name: "Banking Analyst",
    categoryId: "business",
    subcategory: "Finance",
    aliases: ["Banking", "Finance", "Investment Banking"],
    description: "Supports banking transactions, analysis and client work.",
  },
];

/**
 * The catch-all.
 *
 * Kept genuinely small. This is where a custom role lands when it matches
 * nothing else, so it must not become a dumping ground that competes with the
 * real categories in search results.
 */
export const OTHER_ROLES: Role[] = [
  {
    id: "lawyer",
    name: "Lawyer",
    categoryId: "other",
    subcategory: "Legal",
    aliases: ["Legal", "Solicitor", "Attorney"],
    description: "Advises on and drafts legal matters.",
  },
  {
    id: "legal-counsel",
    name: "Legal Counsel",
    categoryId: "other",
    subcategory: "Legal",
    aliases: ["Legal", "In-house Counsel"],
    description: "In-house legal advice for a business.",
  },
  {
    id: "compliance-officer",
    name: "Compliance Officer",
    categoryId: "other",
    subcategory: "Legal",
    aliases: ["Compliance", "Regulatory"],
    description: "Keeps the organisation within its regulatory obligations.",
  },
  {
    id: "teacher",
    name: "Teacher",
    categoryId: "other",
    subcategory: "Education",
    aliases: ["Teaching", "Educator"],
    description: "Teaches a subject to a class.",
  },
  {
    id: "lecturer",
    name: "Lecturer",
    categoryId: "other",
    subcategory: "Education",
    aliases: ["Teaching", "Academic", "Professor"],
    description: "Teaches and assesses at higher-education level.",
  },
  {
    id: "instructional-designer",
    name: "Instructional Designer",
    categoryId: "other",
    subcategory: "Education",
    aliases: ["Learning Design", "Curriculum", "L&D"],
    description: "Designs how a course actually teaches.",
  },
  {
    id: "nurse",
    name: "Nurse",
    categoryId: "other",
    subcategory: "Healthcare",
    aliases: ["Nursing", "Healthcare", "Clinical"],
    description: "Delivers and coordinates patient care.",
  },
  {
    id: "doctor",
    name: "Doctor",
    categoryId: "other",
    subcategory: "Healthcare",
    aliases: ["Physician", "Healthcare", "Medical", "Clinical"],
    description: "Diagnoses and treats patients.",
  },
  {
    id: "pharmacist",
    name: "Pharmacist",
    categoryId: "other",
    subcategory: "Healthcare",
    aliases: ["Pharmacy", "Healthcare", "Clinical"],
    description: "Dispenses medication and advises on its use.",
  },
  {
    id: "healthcare-administrator",
    name: "Healthcare Administrator",
    categoryId: "other",
    subcategory: "Healthcare",
    aliases: ["Healthcare", "Health Administration"],
    description: "Runs the operational side of a healthcare service.",
  },
  {
    id: "supply-chain-analyst",
    name: "Supply Chain Analyst",
    categoryId: "other",
    subcategory: "Supply Chain",
    aliases: ["Supply Chain", "Logistics"],
    description: "Analyses and improves how goods move.",
  },
  {
    id: "supply-chain-manager",
    name: "Supply Chain Manager",
    categoryId: "other",
    subcategory: "Supply Chain",
    aliases: ["Supply Chain", "Logistics", "Procurement"],
    description: "Owns sourcing, inventory and distribution.",
  },
  {
    id: "logistics-coordinator",
    name: "Logistics Coordinator",
    categoryId: "other",
    subcategory: "Supply Chain",
    aliases: ["Logistics", "Supply Chain", "Shipping"],
    description: "Coordinates shipments, carriers and delivery schedules.",
  },
  {
    id: "procurement-specialist",
    name: "Procurement Specialist",
    categoryId: "other",
    subcategory: "Supply Chain",
    aliases: ["Procurement", "Purchasing", "Sourcing"],
    description: "Sources suppliers and negotiates terms.",
  },
  {
    id: "mechanical-engineer",
    name: "Mechanical Engineer",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Mechanical", "Engineering"],
    description: "Designs and analyses mechanical systems.",
  },
  {
    id: "electrical-engineer",
    name: "Electrical Engineer",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Electrical", "Engineering"],
    description: "Designs electrical systems and circuits.",
  },
  {
    id: "civil-engineer",
    name: "Civil Engineer",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Civil", "Engineering", "Structural"],
    description: "Designs and oversees built infrastructure.",
  },
  {
    id: "industrial-engineer",
    name: "Industrial Engineer",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Industrial", "Engineering", "Process"],
    description: "Improves how production systems and processes run.",
  },
  {
    id: "manufacturing-engineer",
    name: "Manufacturing Engineer",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Manufacturing", "Production", "Engineering"],
    description: "Designs and improves manufacturing processes.",
  },
  {
    id: "architect-building",
    name: "Architect",
    categoryId: "other",
    subcategory: "Engineering",
    aliases: ["Architecture", "Building Design"],
    description: "Designs buildings and the spaces in them.",
  },
  {
    id: "executive-assistant",
    name: "Executive Assistant",
    categoryId: "other",
    subcategory: "Administration",
    aliases: ["EA", "Executive Support", "Administration"],
    description: "Supports an executive across scheduling and coordination.",
  },
  {
    id: "office-administrator",
    name: "Office Administrator",
    categoryId: "other",
    subcategory: "Administration",
    aliases: ["Admin", "Administration", "Office Manager"],
    description: "Keeps an office and its administration running.",
  },
  {
    id: "hospitality-manager",
    name: "Hospitality Manager",
    categoryId: "other",
    subcategory: "Hospitality",
    aliases: ["Hospitality", "Hotel"],
    description: "Runs a hospitality operation and its team.",
  },
];
