import { existsSync } from "node:fs";
import { join } from "node:path";

import type { Page } from "@playwright/test";

import { expect, test } from "./fixtures";

/**
 * How long a candidate waits between finishing an answer and hearing the next
 * question.
 *
 * This is measured against the real service, with real speech, because every
 * component on the path -- the voice-activity detector, the model, and the audio
 * scheduler -- belongs to someone else. The numbers here are the only honest
 * basis for claiming the pipeline is or is not fast.
 *
 * Chrome is given a WAV file as its microphone (`--use-file-for-fake-audio-capture`),
 * so the candidate's "answer" is identical between runs and the comparison is
 * meaningful. The fixtures are generated by scripts/make-speech-fixtures.mjs;
 * the specs skip rather than fail when they are absent, so a checkout without
 * them is not a broken build.
 */

const AUDIO_DIR = join(process.cwd(), "e2e", "fixtures", "audio");
const LONG_ANSWER = join(AUDIO_DIR, "long-answer.wav");

interface TurnLatency {
  turn: number;
  speechEndToFirstAudio: number | null;
  speechEndToTranscript: number | null;
  transcriptToFirstAudio: number | null;
  firstAudioToPlayback: number | null;
  replyDuration: number | null;
}

/** Chrome flags that replace the microphone with a recording of real speech. */
function speechFrom(file: string) {
  return {
    launchOptions: {
      args: [
        "--use-fake-device-for-media-stream",
        "--use-fake-ui-for-media-stream",
        "--autoplay-policy=no-user-gesture-required",
        `--use-file-for-fake-audio-capture=${file}`,
      ],
    },
  };
}

async function startInterview(page: Page) {
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: /Start interview/i }).click();
  await expect(page.getByTestId("interview-clock")).toBeVisible({ timeout: 45_000 });
}

/** Reads the timings the provider recorded inside its WebSocket callbacks. */
async function readLatency(page: Page): Promise<TurnLatency[]> {
  return page.evaluate(
    () => (window as unknown as { __voiceLatency?: TurnLatency[] }).__voiceLatency ?? []
  );
}

async function endInterview(page: Page) {
  const end = page.getByRole("button", { name: "End", exact: true });
  if ((await end.count()) === 0) return;
  await end.click();
  await page.getByRole("button", { name: "End interview" }).click();
}

test.use(speechFrom(LONG_ANSWER));

test.describe("turn latency @dev", () => {
  test("the next question follows quickly after a long answer", async ({
    page,
    signIn,
    seedInterview,
  }) => {
    test.skip(!existsSync(LONG_ANSWER), "Run scripts/make-speech-fixtures.mjs first.");

    await signIn("pro");
    const interviewId = await seedInterview({ durationSeconds: 300 });

    await page.goto(`/interview/${interviewId}?devDurationSeconds=150`);
    await startInterview(page);

    // Wait for the interviewer to open, then let the recorded answer play
    // through and fall silent. The fixture ends in three seconds of silence,
    // which is what the detector keys off.
    await expect(page.locator(".transcript")).toBeVisible({ timeout: 60_000 });

    await expect
      .poll(async () => (await readLatency(page)).length, { timeout: 120_000 })
      .toBeGreaterThan(0);

    const turns = await readLatency(page);
    const measured = turns
      .map((t) => t.speechEndToFirstAudio)
      .filter((v): v is number => v !== null);

    console.log("=========== TURN LATENCY ===========");
    for (const turn of turns) {
      console.log(
        `turn ${turn.turn}: speech end -> first audio ${turn.speechEndToFirstAudio}ms ` +
          `(transcript ${turn.speechEndToTranscript}ms, model ${turn.transcriptToFirstAudio}ms, ` +
          `playback +${turn.firstAudioToPlayback}ms)`
      );
    }
    const sorted = measured.slice().sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    console.log(
      `turns: ${measured.length} | best ${sorted[0]}ms | median ${median}ms | worst ${sorted[sorted.length - 1]}ms`
    );
    console.log("=========== END ===========");

    expect(measured.length).toBeGreaterThan(0);
    // A generous ceiling. The point is to catch a regression back into the
    // multi-second territory this work was about, not to pin the number a
    // third-party service happens to return today.
    expect(median).toBeLessThan(4000);

    await endInterview(page);
  });
});
