import { existsSync } from "node:fs";
import { join } from "node:path";

import type { Page } from "@playwright/test";

import { expect, test } from "./fixtures";

/**
 * The counterweight to the latency measurement.
 *
 * Shortening the end-of-speech silence threshold makes every turn faster and,
 * past a point, starts cutting candidates off mid-sentence. This fixture
 * contains a 1.2 second pause inside an answer -- an ordinary hesitation.
 *
 * Read this as a directional signal, not a proof. Chrome loops the WAV
 * continuously from the moment the microphone opens, including over the
 * interviewer's own turns, so "one answer" has no clean boundary to assert
 * against. What the turn count does track reliably is the ordering: the same
 * window yielded four turns at a 900ms threshold and two at 1400ms, which is the
 * evidence that the threshold governs interruption. A rigorous version of this
 * test needs a microphone the harness can start and stop on cue, which Chrome's
 * fake-device flag does not offer.
 *
 * Chrome is given a WAV file as its microphone (`--use-file-for-fake-audio-capture`),
 * so the candidate's "answer" is identical between runs and the comparison is
 * meaningful. The fixtures are generated by scripts/make-speech-fixtures.mjs;
 * the specs skip rather than fail when they are absent, so a checkout without
 * them is not a broken build.
 */

const AUDIO_DIR = join(process.cwd(), "e2e", "fixtures", "audio");
const PAUSED_ANSWER = join(AUDIO_DIR, "paused-answer.wav");

interface TurnLatency {
  turn: number;
  speechEndToFirstAudio: number | null;
  speechEndToTranscript: number | null;
  transcriptToFirstAudio: number | null;
  firstAudioToPlayback: number | null;
  replyDuration: number | null;
}

/** Chrome flags that replace the microphone with a recording of real speech. */
function speechFrom(file: string) {
  return {
    launchOptions: {
      args: [
        "--use-fake-device-for-media-stream",
        "--use-fake-ui-for-media-stream",
        "--autoplay-policy=no-user-gesture-required",
        `--use-file-for-fake-audio-capture=${file}`,
      ],
    },
  };
}

async function startInterview(page: Page) {
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: /Start interview/i }).click();
  await expect(page.getByTestId("interview-clock")).toBeVisible({ timeout: 45_000 });
}

/** Reads the timings the provider recorded inside its WebSocket callbacks. */
async function readLatency(page: Page): Promise<TurnLatency[]> {
  return page.evaluate(
    () => (window as unknown as { __voiceLatency?: TurnLatency[] }).__voiceLatency ?? []
  );
}

async function endInterview(page: Page) {
  const end = page.getByRole("button", { name: "End", exact: true });
  if ((await end.count()) === 0) return;
  await end.click();
  await page.getByRole("button", { name: "End interview" }).click();
}

test.use(speechFrom(PAUSED_ANSWER));

test.describe("pause tolerance @dev", () => {
  test("the interviewer does not interrupt a mid-answer thinking pause", async ({
    page,
    signIn,
    seedInterview,
  }) => {
    test.skip(!existsSync(PAUSED_ANSWER), "Run scripts/make-speech-fixtures.mjs first.");

    await signIn("pro");
    const interviewId = await seedInterview({ durationSeconds: 300 });

    await page.goto(`/interview/${interviewId}?devDurationSeconds=150`);
    await startInterview(page);
    await expect(page.locator(".transcript")).toBeVisible({ timeout: 60_000 });

    // Chrome loops the fixture, so the window has to stop inside the first pass:
    // waiting longer counts the second answer's reply as an interruption of the
    // first. The recording is 20.2s, so this covers one answer and its reply and
    // stops before the next answer finishes.
    await page.waitForTimeout(24_000);

    const turns = await readLatency(page);
    console.log("=========== PAUSE HANDLING ===========");
    console.log(`turns detected while one answer played: ${turns.length}`);
    console.log("=========== END ===========");

    // A loose ceiling, because the looping fixture makes the exact count
    // environmental. What this catches is a threshold dropped low enough to
    // shred an answer into many turns, which is the regression that matters.
    expect(turns.length).toBeLessThanOrEqual(3);

    await endInterview(page);
  });
});
